# Tema de tu página
theme: jekyll-theme-minimal

# Título de tu sitio
title: Chisco.dev

# Descripción de tu sitio
description: Estudiante de informática | Compartiendo proyectos e ideas sobre tecnología 🚀
